### ISSUE TITLE
Noises Playing While Tanks Are Still

### ISSUE THREAD

**Issue by ChrisLTheNerd** [Crescentine/Trajans-Tanks-1.18#1]
The tanks keep making noises at random, even when they are completely still. The Anti-Tank Artillery also has the same issue. I'm using file [Trajan's Tanks 1.18.2 (2.2)] and forge-40.1.0

https://user-images.githubusercontent.com/50182206/177022987-fed85968-0a8f-4ad1-a242-d6c2ee3a1076.mp4

**Comment by Crescentine** [comment]
Thank you for bring this to my attention; I will handle this in the next patch.

Unfortunately, my computer broke a few days ago and so I've been unable to work on the mod, but my new laptop will arrive by the end of the week. 

Thanks for playing the mod.

**Comment by Crescentine** [comment]
Minecraft requires an "ambient" sound, so I just set it to one less noticeable. It should be better now. :)
