### ISSUE TITLE
Tanks and artillery are affected by potions

### ISSUE THREAD

**Issue by GuineaPigMart** [Crescentine/Trajans-Tanks-1.18#2]
The tanks and artillery are affected by potions. That isn't logical and I can't turn it off. Can you make it so that tanks and artillery are not affected by potions? (I'm using version 2.21 for 1.18)

**Comment by Crescentine** [comment]
I will look into this, I’ve been aware of it for a while. Although if it is to be fixed it would only be for 1.19/latest version unless I decide in the future to fully back port to 1.18.

**Comment by Crescentine** [comment]
i changed it to not happen for the next update.
