### ISSUE TITLE
[1.20.1] Crash upon entering tank

### ISSUE THREAD

**Issue by MrKashew** [Crescentine/Trajans-Tanks-1.18#3]
[crash-2023-06-28_20.47.14-client.txt](https://github.com/Crescentine/Trajans-Tanks/files/11901804/crash-2023-06-28_20.47.14-client.txt)

**Comment by hisRoyalty** [comment]
@MrKashew Please check if the issue persists in the latest beta version. Nothing of this sort occurs for me.

**Comment by hisRoyalty** [comment]
Seems that its working.
