### ISSUE TITLE
Client crash trying to render a "QF-6"

### ISSUE THREAD

**Issue by dhgameryt** [Crescentine/Trajans-Tanks-1.18#4]
Client crash trying to render a "QF-6"
forge 47.1.1, trajan tanks 1.20.1-2.4 and trajan core 1.51-1.20.1
crash report: https://gist.github.com/dhgameryt/9d75dbc94c86f3784e472a509138e092

**Comment by hisRoyalty** [comment]
fixed in the newest commit and version will be released soon
