### ISSUE TITLE
crash 1.20.1 log in desc, i have no idea

### ISSUE THREAD

**Issue by Veruty** [Crescentine/Trajans-Tanks-1.18#8]
[crash-2024-09-13_03.54.40-client.txt](https://github.com/user-attachments/files/16985437/crash-2024-09-13_03.54.40-client.txt)

**Comment by hisRoyalty** [comment]
You are using "Trajan's Core 1.6 - Early Alpha DO NOT USE.jar", which in the name instructs one not to use it. You are probably using a mismatched version. Use the latest release build instead.
